services:
  martin:
    image: ghcr.io/maplibre/martin:latest
    container_name: martin
    restart: unless-stopped
    command: ["--webui", "enable-for-all", "/data"]
    volumes:
      - ./data:/data:ro
    ports:
      - "43000:3000"   # ⬅️ antes 3000

  map-viewer:
    image: nginx:alpine
    container_name: map-viewer
    restart: unless-stopped
    volumes:
      - ./viewer:/usr/share/nginx/html:ro
    ports:
      - "48081:80"     # ⬅️ antes 8081
